name: to_do_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
          weight: 900
